### ISSUE TITLE
LTI Embed Fails in AWS Avalon

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#202]
```OAuth::Signature::UnknownSignatureMethod (OAuth::Signature::UnknownSignatureMethod):
  oauth (0.5.3) lib/oauth/signature.rb:17:in `build'
  ims-lti (1.1.13) lib/ims/lti/request_validator.rb:20:in `valid_request?'
  ims-lti (1.1.13) lib/ims/lti/request_validator.rb:42:in `valid_request!'
  /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bundler/gems/omniauth-lti-7534c44fc5a3/lib/omniauth/strategies/lti.rb:18:in `callback_phase'
  omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.8) lib/rack/etag.rb:24:in `call'
  rack (1.6.8) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.8) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.8) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.8) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  active-fedora (11.3.0) lib/active_fedora/ldp_cache.rb:26:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  lograge (0.5.1) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:22:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  puma (2.16.0) lib/puma/configuration.rb:81:in `call'
  puma (2.16.0) lib/puma/server.rb:557:in `handle_request'
  puma (2.16.0) lib/puma/server.rb:404:in `process_client'
  puma (2.16.0) lib/puma/server.rb:270:in `block in run'
  puma (2.16.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'```

**Comment by carrickr** [comment]
@davidschober 

To add Avalon items you need to hit the Course Reserves tool on the left hand column.  Then streaming video or audio.  However no items have been added to this course so there is nothing to add.  

Just dropping in the URL won't work, the tool has to be used.  So to test this we need to get course reserves to add an item to the course and then access it via tool.

If you want to test this we either need to add some items to the test course or get added to a course with items as a student and check the links.

**Comment by carrickr** [comment]
URL was being generated in Avalon, not via the LTI tool.  Doc this for future reference and close.

**Comment by carrickr** [comment]
We had two issues here:

First was a missed fix from core Avalon.  Handled in PR #209 

The second was we only had the `SETTINGS__DOMAIN__HOST` pulled out from our `avalon.yml` in the AWS config.  We needed `SETTINGS__DOMAIN__PROTOCOL = https` and `SETTINGS__DOMAIN__PORT = 443` as well.  As they are in the pre environmental config avalon.  

Changed these two and deployed.
