### ISSUE TITLE
NU Avalon spinner Safari issues

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#245]
### Description
The custom NU Avalon loading spinner is causing issues clicking on section links in MediaElement players in Safari.

### Done Looks Like
Investigate what is causing the issue and fix so Safari section links are able to be clicked and played normally.

**Comment by adamjarling** [comment]
@mbklein @carrickr I'm still getting an error trying to run the `nu-develop` branch locally.  Attached is a screen shot.  Here's some additional output:

```
Started GET "/" for ::1 at 2017-09-28 08:32:48 -0700
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by CatalogController#index as HTML
   (0.4ms)  SELECT COUNT(*) FROM "role_maps"
  RoleMap Load (0.2ms)  SELECT "role_maps".* FROM "role_maps" WHERE "role_maps"."parent_id" IS NULL
  RoleMap Load (0.3ms)  SELECT "role_maps".* FROM "role_maps" WHERE "role_maps"."parent_id" = ?  [["parent_id", 1]]
  RoleMap Load (0.1ms)  SELECT "role_maps".* FROM "role_maps" WHERE "role_maps"."parent_id" = ?  [["parent_id", 3]]
  RoleMap Load (0.1ms)  SELECT "role_maps".* FROM "role_maps" WHERE "role_maps"."parent_id" = ?  [["parent_id", 5]]
Usergroups are ["public", "::1"]
Completed 500 Internal Server Error in 382ms (ActiveRecord: 2.0ms)

Blacklight::Exceptions::InvalidRequest (RSolr::Error::Http - 404 Not Found
Error:     Not Found

URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby&rows=0&q=_query_%3A%22%7B%21raw+f%3Dhas_model_ssim%7DAdmin%3A%3ACollection%22&qt=standard

Backtrace: /Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
(eval):2:in `get'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/solr_service.rb:44:in `get'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/solr_service.rb:65:in `count'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/relation/calculations.rb:11:in `count'
/Users/aja0137/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/querying.rb:3:in `count'
/Users/aja0137/Documents/nulib-repositories/nulib/avalon/lib/hydra/multiple_policy_aware_access_controls_enforcement.rb:29:in `block in policies_with_access'
```
![nu-avalon-blacklight-error-screen.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f241a85cf39f254f207b3d49a639628af165ac4169040a015cb053181d1ba6acda6fb4bc2e758d585ebbd23b5f71c36816a8ec804dbf05ef20884786b0ae965e82b96371b8d6d6056b5c17129bfe543fa19c4bce5ef748e14856a0123071ab.png)

**Comment by davidschober** [comment]
abandoned
