### ISSUE TITLE
User Can't upload from Dropbox

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#286]
## Description

User can't upload files from dropbox or via web interface.

To recreate:

- Go to media.northwestern.edu
- login
- upload an item via cyberduck
- click on Manage Content--> Create an Item
- Click up upload via drobpox
- try to attach file, see "We're sorry Something Went Wrong"

OR

- Click on upload item
- find file locally
- click upload
- See "We're sorry Something Went Wrong" 

## User Email

I’m having trouble uploading to Avalon. 

Within Avalon I’m trying to upload from the dropbox. I can see the list of items in the dropbox, but after selecting what I need it doesn’t load properly and I’m hit with the “we’re sorry, but something went wrong” error message. I’m using Firefox if that matters.

**Comment by davidschober** [comment]
@mbklein and @carrickr this is reproducible can you jump on it?

**Comment by davidschober** [comment]
```I, [2017-12-12T16:57:04.229285 #26106]  INFO -- : method=GET path=/ format=*/* controller=CatalogController action=index status=200 duration=276.43 view=164.61 db=4.23 time=2017-12-12 16:57:03 +0000
I, [2017-12-12T16:57:04.337878 #26106]  INFO -- : [Aws::S3::Client 200 0.074266 0 retries] head_object(bucket:"avalon-masterfiles-cfx3wj9",key:"uploads/0e580a2a-5522-4591-a34e-6c55ff289310/BigBuckBunny_320x180.mp4")  

I, [2017-12-12T16:57:04.381623 #26106]  INFO -- : [Aws::S3::Client 0 0.000765 0 retries] get_object(bucket:"avalon-masterfiles-cfx3wj9",key:"uploads/0e580a2a-5522-4591-a34e-6c55ff289310/BigBuckBunny_320x180.mp4")  

I, [2017-12-12T16:57:04.431130 #26106]  INFO -- : method=GET path=/is_it_alive format=*/* controller=ApplicationController action=alive status=200 duration=1.15 view=0.51 db=0.00 time=2017-12-12 16:57:04 +0000
I, [2017-12-12T16:57:04.535289 #26110]  INFO -- : method=GET path=/ format=*/* controller=CatalogController action=index status=200 duration=198.75 view=134.59 db=5.30 time=2017-12-12 16:57:04 +0000
I, [2017-12-12T16:57:04.882801 #26106]  INFO -- : method=GET path=/is_it_alive format=*/* controller=ApplicationController action=alive status=200 duration=1.15 view=0.53 db=0.00 time=2017-12-12 16:57:04 +0000
W, [2017-12-12T16:57:05.157042 #26106]  WARN -- : Could not find workflow for: #<MasterFile:0x000056254f871958>
I, [2017-12-12T16:57:05.159558 #26106]  INFO -- : method=POST path=/master_files format=html controller=MasterFilesController action=create status=500 error='NoMethodError: undefined method `master_files' for nil:NilClass' duration=1241.95 view=0.00 db=4.02 time=2017-12-12 16:57:03 +0000
F, [2017-12-12T16:57:05.160310 #26106] FATAL -- : 
NoMethodError (undefined method `master_files' for nil:NilClass):
  app/models/master_file.rb:702:in `update_parent!'
  app/services/master_file_builder.rb:33:in `block in from_specs'
  app/services/master_file_builder.rb:22:in `each'
  app/services/master_file_builder.rb:22:in `from_specs'
  app/services/master_file_builder.rb:16:in `build'
  app/controllers/master_files_controller.rb:167:in `create'

```


[10:58] 
so this is also failing when I try to upload a file, the whole create page is broken

**Comment by davidschober** [comment]
Media info got updated... Avalon needed to pin to a prior version @mbklein @carrickr can you confirm?

**Comment by davidschober** [comment]
Closing @Nic4Images let me me know if you need anything else
