### ISSUE TITLE
Throttle BatchIngest on AWS

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#313]
I'm seeing errors coming out of Fedora on batch.  

```=> "STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key \"1c6c6a8b67d2b2ca9d160423b99bdcc00ff205f7\" within binary store at \"/var/cache/tomcat8/temp/modeshape-binary-store\"\n\tat org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:213)\n\tat org.modeshape.jcr.value.binary.AbstractBinaryStore.storeValue(AbstractBinaryStore.java:251)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:257)\n\tat org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:49)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:149)\n\tat org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:41)\n\tat org.fcrepo.kernel.modeshape.FedoraBinaryImpl.setContent(FedoraBinaryImpl.java:179)\n\tat org.fcrepo.http.api.ContentExposingResource.replaceResourceBinaryWithStream(ContentExposingResource.java:622)\n\tat org.f...""```

I think we might be overloading Fedora with our batch, since Amazon can blow through transcoding so fast we're hammering too many objects into Fedora in too short of a run.  We may need to throttle these particular jobs or rewrite it to not queue all at once.

**Comment by carrickr** [comment]
So there are two things going on here:

First for Fedora.  If we have 20 Elastic Transcoder jobs (the max allowed by AWS) that means there will be 100 writes to Fedora (media object, masterfile, and derivatives are all written at the end of transcoding).  In my case I was using the same bunny video for all my objects so all 20 jobs finished at the same time so that was 100 writes to Fedora in a very brief window.  In a real world all the items will have varying sizes so the transcode jobs should theoretically be spaced out.

The second issue is that Elastic Transcoder allows you to queue 2 jobs a second, with brief bursts of 100 per second allowed.  In the case of demo day I definitely blew over the burst limit and then ran into the issue of being locked to 2 per second.  In production use people don't batches back to back as aggressively as I was we're unsure if this problem will manifest.

@jenyoung has a batch of ~1,500 audio files that will be going into production.  So she'll test that and see if it breaks.  We'll then do any throttling based on that.  The core problem with throttling is that as long as we're under burst limit it's unneeded, but we have no great way to determine if we're over burst or not, be aware of what's going on in the UI (where users can be uploading items and trigging create jobs in Elastic Transcode that count toward the cap, etc).  So we're either throttling pretty much everything or doing a major rewrite of the transcode pipeline so we can track and know if we have burst.

**Comment by carrickr** [comment]
```Suo::LockClientError: Suo::LockClientError
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/suo-0.3.2/lib/suo/client/base.rb:153:in `rescue in retry_with_timeout'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/suo-0.3.2/lib/suo/client/base.rb:140:in `retry_with_timeout'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/suo-0.3.2/lib/suo/client/base.rb:101:in `acquire_lock'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/suo-0.3.2/lib/suo/client/base.rb:30:in `lock'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/throttle.rb:38:in `block (3 levels) in <module:Throttle>'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/base.rb:70:in `block in with_lock_client'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/base.rb:64:in `with_raw_client'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/base.rb:69:in `with_lock_client'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-traffic_control-0.1.3/lib/active_job/traffic_control/throttle.rb:37:in `block (2 levels) in <module:Throttle>'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:441:in `instance_exec'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:441:in `block in make_lambda'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:342:in `block in simple'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:497:in `block in around'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
... 29 levels...
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-4.2.9/lib/active_job/execution.rb:31:in `perform_now'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activejob-4.2.9/lib/active_job/execution.rb:16:in `perform_now'
	from (irb):3:in `block in irb_binding'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-4.2.9/lib/active_record/relation/delegation.rb:46:in `each'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/activerecord-4.2.9/lib/active_record/relation/delegation.rb:46:in `each'
	from (irb):3
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/console.rb:110:in `start'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/console.rb:9:in `start'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /opt/rubies/ruby-2.3.5/lib/ruby/gems/2.3.0/gems/railties-4.2.9/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'```

Code is up but retries are failing due to Suo having trouble

**Comment by carrickr** [comment]
May be memcache server error

**Comment by carrickr** [comment]
@davidschober @mbklein 

So this is fixed in the second we can now get batches through, but it's not optimal yet.

What've done is add in throttling via active_job traffic control and config variables so we can tweak it without changes:

```
SETTINGS__BATCH_THROTTLING__INGEST_JOBS_THROTTLE_THRESHOLD
SETTINGS__BATCH_THROTTLING__INGEST_JOBS_SPACING
SETTINGS__BATCH_THROTTLING__UPDATE_JOBS_THROTTLE_THRESHOLD
SETTINGS__BATCH_THROTTLING__UPDATE_JOBS_SPACING
```

The not so awesome problem is that the above translates into let one job run every ten seconds.  When a job tries to run and gets told "Nope, another ran 9 seconds ago" it sleeps for 1x to 5x the timeout (10 seconds) and then retries.  We can't control that 1x to 5x without forking the traffic code gem since it's coded into there.  So that means potentially 50 seconds of sleep.

You do that over say that 3,500 item production workload and even at best its 6 jobs a minute, which is pushing 10 hours.  

I was trying two jobs every 5 seconds and that failed.  This is due to the fact that apparently there is a specific Fedora issue with S3 and multiple jobs, you have to space them out to ensure nothing overlaps.  So while we might be able to able to get better than 1 every 10 seconds, we won't get fast.

MBK is looking at compiling a Fedora that has a bespoke modeshape fix for S3 and if that works we can deploy that and then mess with this further.  For the purpose of being able to test at least.

**Comment by carrickr** [comment]
150 item test batch went through

**Comment by carrickr** [comment]
Documented here: https://github.com/nulib/avalon/wiki/Throttling-Batch-Ingest-on-AWS

**Comment by carrickr** [comment]
With our bespoke Fedora we are now at:

**Submission to Elastic Transcoder** 2 jobs every 5 seconds
**ActiveEncode Updates** 3 jobs every 10 seconds

For the former throttle, each submission also implies creation of the MediaObject and MasterFile(s) prior to submission of the job.  So that's a minimum of 2 Fedora writes per row of the spreadsheet.  More for complex objects.

Assuming the worst case, were you submit 2 items, then face the 5x timeout before you can submit 2 more, it would still take under 4 minutes to fill all 20 lanes of the ElasticTranscode queue.  After that all submits would be queued inside Elastic Trancoder for when a lane opens up (MediaObject and MasterFile creation would continue to occur).  In reality we'll probably fill up all the lanes in under 2 minutes since the timeout is 1x to 5x.

I think this is a pretty good rate both in terms of getting transcodes going and not stressing Fedora too much.

For the latter throttle, this means if all 20 transcodes finished at the same time it would take a minimum of 70 seconds to write them all back to Fedora.  Max would be 350 seconds or about 6 minutes.  I wish we could be a bit more aggressive here, but I'm leery to push this because this is the most expensive part.  For 20 MediaObjects that each have one MasterFile you end up with 100 Fedora writes (more writes if you have more MasterFiles).  

Once Staging is clear for testing again I'm going to test a higher count batch (currently I've been doing 150 item batches) to make sure the current settings can stand up to it.  I think both throttles are pretty reasonable since most of what we transcode is in the form of performances, TV episodes, or movies all of which take time to transcode.  So once we have the queue filled it will stay full and the updates should end naturally spread out due to the varying length of content.

**Comment by carrickr** [comment]
Also just for the record, batches may show varying counts between total and moving image/sound as the jobs catch up

<img width="348" alt="screen shot 2018-01-11 at 6 44 11 pm" src="https://user-images.githubusercontent.com/5350060/34853025-92c04bfe-f6ff-11e7-9a0f-ea5d9edb7767.png">

**Comment by carrickr** [comment]
With the better ActivRecord pools (pool size 40) this is now working
