### ISSUE TITLE
Ingest Finished Emails Fail on AWS

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#317]
```I, [2018-01-08T16:41:23.166464 #24210]  INFO -- : Performing IngestBatchStatusEmailJobs::IngestFinished from BetterActiveElasticJob(ingest_finished_job)
I, [2018-01-08T16:41:23.193815 #24210]  INFO -- : Attempted to init base path `avr`, but it already exists
I, [2018-01-08T16:41:23.279097 #24210]  INFO -- : Performed IngestBatchStatusEmailJobs::IngestFinished from BetterActiveElasticJob(ingest_finished_job) in 112.4ms
F, [2018-01-08T16:41:23.280639 #24210] FATAL -- : 
ActionView::Template::Error ():
    47:     </tr>
    48:     <% @completed_items.each do |be_completed| %>
    49:       <tr>
    50:         <% media_object = MediaObject.find(be_completed.media_object_pid) %>
    51:         <% link_url = media_object.permalink %>
    52:         <% link_url = media_object_url(media_object) if link_url.blank? %>
    53:         <td> <%= be_completed.position + 2 %> </td>
  app/views/batch_registries_mailer/batch_registration_finished_mailer.html.erb:50:in `block in _app_views_batch_registries_mailer_batch_registration_finished_mailer_html_erb__2507769065659346002_47453990286800'
  app/views/batch_registries_mailer/batch_registration_finished_mailer.html.erb:48:in `_app_views_batch_registries_mailer_batch_registration_finished_mailer_html_erb__2507769065659346002_47453990286800'
  app/mailers/batch_registries_mailer.rb:34:in `batch_registration_finished_mailer'
  app/jobs/ingest_batch_status_email_jobs.rb:34:in `block in perform'
  app/jobs/ingest_batch_status_email_jobs.rb:23:in `perform'
```

This does not occur on spruce or non AWS environments

**Comment by carrickr** [comment]
This is partly modeshape and partly the fault of the mailer not handling deletions prior to the status email being sent (and then me doing just that)/

Core ticket dropped to enhance this:

https://github.com/avalonmediasystem/avalon/issues/2743
